name: Append to array

on:
  workflow_dispatch:

env:
  PROJECTS: ("Pippo")
  
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
    - name: 🚀 Append to array
      run: |
        temp=(${PROJECTS})
        echo ${temp[@]}
        temp+=("Mirco")
        echo ${temp[@]}
        echo "PROJECTS=$temp" >> $GITHUB_ENV
        echo ${PROJECTS}
