# https://gist.github.com/magnetikonline/0ca47c893de6a380c87e4bdad6ae5cf7
# https://unix.stackexchange.com/questions/328882/how-to-add-remove-an-element-to-from-the-array-in-bash
name: Append to array

on:
  workflow_dispatch:

env:
  PROJECTS: ("Pippo")
  
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
    - name: 🚀 Append to array
      run: |
        temp=${{env.PROJECTS}}
        temp+=("Mirco")
        echo ${temp[@]}
        echo "PROJECTS=${temp[@]}" >> $GITHUB_ENV
    - run: echo ${{env.PROJECTS}}
