name: Append to array

on:
  workflow_dispatch:

env:
  PROJECTS: ()
  
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
    - name: 🚀 Append to array
      run: |
        temp=${PROJECTS}
        temp+=('Mirco')
        echo "PROJECTS=$temp" >> $GITHUB_ENV
