name: Reusable workflow example

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        
jobs:
  setup:
    name: bump-revision
    runs-on: ubuntu-latest
    steps:    
      - name: ⚙️ Bump if alpha.
        id: bump-with-alpha
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
                const incoming = "${{ inputs.version }}"
                console.log("Incoming Tag: " + incoming)
                if(incoming.includes('alpha')) {
                  const oldNum = incoming.match(/alpha[.]*(\d+)/)[1]
                  const newNum = parseInt(oldNum)+1
                  const newTag = incoming.replace(/alpha.*\d+/, `alpha.${newNum}`)
                  console.log("New Tag: " + newTag)
                  return newTag
                }
                else {
                  const newTag =incoming +'-alpha.0'
                  console.log("New Tag: " + newTag)
                  return newTag
                }
                
      - shell: bash
        run: |
          expr "${{steps.bump-with-alpha.outputs.result}}" > revision.txt
      - name: Upload revision
        uses: actions/upload-artifact@v2
        with:
          name: revision
          path: revision.txt
