name: Checks for changes

on:
  push:
  
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version proj
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: ./Gh-Components/Gh-Components.csproj 
    - name: bumping version
      uses: sonomirco/module-repo/.github/workflows/bump-version.yml@main
      with:
        version: ${{steps.get-version.outputs.version}}
    - id: setversion
      run: | 
        packageversion="${{steps.get-version.outputs.version}}"
        echo $packageversion
        echo "::set-output name=version::$packageversion"

    # For pull requests it's not necessary to checkout the code
    - name: Check which services were modified
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          project1: 'Gh-Components/**'
          project2: 'ModulComponents/**'
          
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
      output2: ${{ steps.setversion.outputs.version }}

  # JOB to build and test each of modified packages
  build:
    runs-on: ubuntu-latest
    needs: changes
    steps:
    - run: echo ${{needs.changes.outputs.output2}}
    
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "new-json-file.json"
        json: '{"name":"jsdaniell", "password":"mypass"}'   
        
    - name: 📜 Display
      id: set_var
      run: |
          content=`cat ./new-json-file.json`
          echo "::set-output name=packageJson::$content"
          echo ${{ fromJSON(needs.changes.outputs.packages) }}
          echo ${{ steps.create-json.outputs.full-path }}   
          
    - run: echo ${{fromJson(steps.set_var.outputs.packageJson).name}}
