name: Checks for changes

on:
  workflow_dispatch:
  
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # For pull requests it's not necessary to checkout the code
    - name: Check which services were modified
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          Gh-Components: 'Gh-Components/**'
          ModulComponents: 'ModulComponents/**'
        

  # JOB to build and test each of modified packages
  build:
    needs: changes
    strategy:
      matrix:
        packages: ${{ fromJson(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{needs.changes.outputs.output2}}
    
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "new-json-file.json"
        json: '{"name":"jsdaniell", "password":"mypass"}'   
        
    - name: 📜 Display
      id: set_var
      run: |
          content=`cat ./new-json-file.json`
          echo "::set-output name=packageJson::$content"
          echo ${{ fromJSON(needs.changes.outputs.packages) }}
          echo ${{ steps.create-json.outputs.full-path }}   
          
    - run: echo ${{fromJson(steps.set_var.outputs.packageJson).name}}
