name: Checks for changes

on:
  push:
  
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - name: Check which services were modified
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          project1: 'Gh-Components/**'
          project2: 'ModulComponents/**'

  # JOB to build and test each of modified packages
  build:
    needs: changes
    runs-on: ubuntu-latest
    steps:
    - name: create-json
      uses: schdck/create-env-json@v1
      id: create-env
      with:
        file-name: 'env.json'
        name: 'Mirco'
        email: 'mirco.bianchini@mottmac.com'
    - name: 📜 Display
      run: |
          echo ${{ fromJSON(needs.changes.outputs.packages) }}
          echo ${{ steps.create-env.outputs.full-path }}
          echo ${{ steps.create-env.outputs }}
          echo ${{ steps.create-json.outputs.full-path }}
