name: Checks for changes

on:
  push:
  
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          project1: 'Gh-Components/**'
          project2: 'ModulComponents/**'

  # JOB to build and test each of modified packages
  build:
    needs: changes
    runs-on: ubuntu-latest
    steps:
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "new-json-file.json"
        json: '{"name":"jsdaniell", "password":"mypass"}'
    - name: 📜 Display
      run: |
          echo ${{ fromJSON(needs.changes.outputs.packages) }}
          echo ${{ create-json.output }}
