# https://gist.github.com/magnetikonline/0ca47c893de6a380c87e4bdad6ae5cf7
# https://unix.stackexchange.com/questions/328882/how-to-add-remove-an-element-to-from-the-array-in-bash
name: Python read yaml file

on:
  workflow_dispatch:
  
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.setvar.outputs.variables }}
    steps:
      - id: setvar
        run: | 
          # if we are passing a list to the python script the elements need to be divided.
          # echo "::set-output name=variables::\"Dyn-Module\" \"Gh-Module\""
          # Other solution is passing the list as a string.
          echo "::set-output name=variables::['Dyn-Module', 'Gh-Module']
          
  reading:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - id: bumper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python bump-version.py --modules "${{ needs.changes.outputs.values }}"
      - run: echo ${{ fromJson(steps.bumper.outputs.module_bumped).Dyn-Module }}
            
