# https://gist.github.com/magnetikonline/0ca47c893de6a380c87e4bdad6ae5cf7
# https://unix.stackexchange.com/questions/328882/how-to-add-remove-an-element-to-from-the-array-in-bash
name: Python read yaml file

on:
  workflow_dispatch:
  
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.setvar.outputs.variables }}
    steps:
      - id: setvar
        run: | 
          echo "::set-output name=variables::'[\"Dyn.Module\", \"Gh.Module\"]'"
          
  reading:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: reader
        run: echo ${{ fromJson(needs.changes.outputs.values) }}
            
