# https://gist.github.com/magnetikonline/0ca47c893de6a380c87e4bdad6ae5cf7
# https://unix.stackexchange.com/questions/328882/how-to-add-remove-an-element-to-from-the-array-in-bash
name: Python read yaml file

on:
  workflow_dispatch:
  
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setvar
        run: | 
          echo "::set-output name=variable::Gh.Mod"
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
    
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import yaml
            with open('versions.yaml', 'r') as file:
              prime_service = yaml.safe_load(file)
            
            print(prime_service['Dyn']['Module'])
            
            input = get_input(${{steps.setvar.outputs.variable}}
            print(input)
