# https://gist.github.com/magnetikonline/0ca47c893de6a380c87e4bdad6ae5cf7
# https://unix.stackexchange.com/questions/328882/how-to-add-remove-an-element-to-from-the-array-in-bash
name: Python read yaml file

on:
  workflow_dispatch:
  
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.setvar.outputs.variables }}
    steps:
      - id: setvar
        run: | 
          # if we are passing a list to the python script the elements need to be divided.
          # echo "::set-output name=variables::\"Dyn-Module\" \"Gh-Module\""
          # Other solution is passing the list as a string.
          echo "::set-output name=variables::['Dyn-Module', 'Gh-Module']"
          
  bumping:
    needs: changes
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.bumper.outputs.module_bumped }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - id: bumper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python bump-version.py --modules "${{ needs.changes.outputs.values }}"
      
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Sandbox
          message: 'Updated the yaml file with the versions!'
          add: 'versions.yaml'
            
  reading:
    needs: bumping
    strategy:
      matrix: ${{ fromJSON(needs.bumping.outputs.versions) }}
      fail-fast: true
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
          - run: |
              echo ${{ matrix.Module }}
              echo ${{ matrix.Version }}
